### ISSUE TITLE
Help backport upstream patch to fix SKQP issue

### ISSUE THREAD

**Issue by renchenglei** [intel/external-mesa#102]
SKQP module is new added to Android P, and there are some issues that have been fixed on upstream. Now, we need rebase or backport the fix patch from upstream. @strassek, when will we start next round mesa rebase or could you help backport the fix patch to our github?
There are total 3 SKQP failures:
1. org.skia.skqp.SkQPRunner#gles_mixedtextblobs
Fix patch: eca4a6548d07bbbb02a7768edb397bad7b72cfc2
2. org.skia.skqp.SkQPRunner#unitTest_EGLImageTest
Fix patch: a5c39ed974402c6a40d51c6189547d1f29581fbe
3. org.skia.skqp.SkQPRunner#unitTest_SRGBMipMaps
Fix patch: 337a808062c756b474ee80a9ac04b5a3dbbeb67e

@tpalli @jennycao @js0701 FYI.

**Comment by strassek** [comment]
I've been running into issues with regression testing on Celadon recently, but I'll see if I can get these landed in master.

**Comment by renchenglei** [comment]
Thanks @strassek!

**Comment by strassek** [comment]
@renchenglei I'm still having issues with Celadon, but I've pushed to a branch on my fork that includes the backports in case you want to help test - https://github.com/strassek/external-mesa/tree/18.2.

**Comment by tpalli** [comment]
@strassek what kind of issues?

**Comment by strassek** [comment]
@tpalli on KBL I'm getting periodic adb disconnections that cause the dEQP run to fail out. On APL I'm seeing the system freeze after about 5 minutes of testing. I'm hitting both of these failures even on older revisions of mesa.

**Comment by tpalli** [comment]
@strassek  :/ ok will try to reproduce, I haven't seen such hang in my recent testing, but I don't have the dEQP patches on top

**Comment by renchenglei** [comment]
@tpalli @strassek do you connect DUT with USB cable or network? Sometimes, I also encounter this issue, I connect DUT with network firstly, then connect with USB cable, and disconnect USB cable, it could work well with Network connection. One more thing, if you use USB cable, you need plug in twice. If it still not work, please let me know, I will find some clue on our side.

**Comment by renchenglei** [comment]
@strassek, do you need help verify https://github.com/strassek/external-mesa/tree/18.2? We could ask someone from our side to start one round of CTS GFX(include CTS dEQP) test to check if there will be regression. :)

**Comment by strassek** [comment]
@renchenglei yes, that would be helpful. I've just updated that branch with the patches rebased on 18.2.5.

**Comment by renchenglei** [comment]
@strassek, could you share the test list when you do rebase work every time?

**Comment by strassek** [comment]
Nothing more than the dEQP must pass for Android P. Simple as invoking `run cts -m CtsDeqpTestCases`. You'll need to get your own baseline with the existing sources in master.

**Comment by renchenglei** [comment]
Ok, got it! We will do same as you. And once it is merged to master branch, there will be much more test from QA side.

**Comment by renchenglei** [comment]
@strassek @tpalli, as there is some adb issue on Celadon, we tried on GP, and finish one round of dEQP must pass test, and all cases could pass.

Suite / Plan | CTS / cts-retry
-- | --
Suite / Build | 9.0_r4 / 5106607
Host Info | Result/@start walker (Linux - 4.13.0-36-generic)
Start time / End Time | Mon Nov 26 10:41:42 CST 2018 / Mon Nov 26 10:45:23 CST 2018
Tests Passed | 767266
Tests Failed | 0
Modules Done | 2
Modules Total | 2

**Comment by strassek** [comment]
Thanks for testing, @renchenglei! Candidate branch, containing above fixes, pushed to master.

**Comment by renchenglei** [comment]
Thanks @strassek! Let's close this issue. :)
