### ISSUE TITLE
Help backport upstream patch to fix WebGL regression with latest Chrome(70.0.3538.80)

### ISSUE THREAD

**Issue by renchenglei** [intel/external-mesa#105]
GL_FRAMEBUFFER_FLIP_Y_MESA is added to mesa, and used by latest chrome browser(70.0.3538.80). This extension cause WebGL regression. Upstream mesa already has fix for this issue. @strassek, could you help backport following patch to our mesa? Thanks a lot!
commit 08f97407fb14f53bf9f43dc4165a185418437a6b
(i965: Replace checks for rb->Name with FlipY (v2))

@tpalli @js0701 @jennycao FYI.
Another two patches have already been included in our mesa code.
commit 60d0c0d062b543b85a354e5266aa974fcdc36290
(mesa: FramebufferParameteri parameter checking)

commit ba6cc32cf9337804d744f234a196c97923c84360
(mesa: Additional FlipY applications)

**Comment by tpalli** [comment]
It would make sense to rebase the whole tree to 18.2.5 as there are other fixes available, also Android specific ones.

**Comment by renchenglei** [comment]
@tpalli @strassek, that make sense, and we would help do validation on our side. :)

**Comment by strassek** [comment]
I've updated my candidate branch [1] to be based on 18.2.5, it sounds like @renchenglei will help facilitate regression testing.
[1] https://github.com/strassek/external-mesa/tree/18.2

**Comment by strassek** [comment]
Master is updated with fixes

**Comment by renchenglei** [comment]
Thanks @strassek, let's close this issue! :)
