### ISSUE TITLE
Crashes in dEQP-VK.spirv_assembly.instruction.compute*

### ISSUE THREAD

**Issue by strassek** [intel/external-mesa#112]
Seen as late as CTS 9.0_r8

Upstream Mesa has added some checks which reject SPIR-V programs that break certain rules. That rejection causes compilation to fail and hence offending tests are crashing.

Commit 5c3cb9c3ce3f9fb05c22536c30a68a7b09300642 adds error checking for Block and BufferBlock decorations.
Commit 63b9aa2e257475cdee0a1aafcd57c6f123d6e7e6 asserts that if a pointer doesn't have a block_index it must be a pointer to the variable itself.

**Comment by strassek** [comment]
The dEQP dev branch includes a fix for this issue: https://android.googlesource.com/platform/external/deqp/+/1dbdfe34947fdb3e6d24226a58f02d0b8a515da8

**Comment by strassek** [comment]
Crashes have been fixed in CTS 9.0_r9. There does seem to be a lingering timeout issue in one of the cases, but we can track that separately.

**Comment by jennycao** [comment]
Great！Thanks for your follow up ！
