### ISSUE TITLE
Segfault - intel_disable_rb_aux_buffer in brw_draw.c

### ISSUE THREAD

**Issue by sevagh** [intel/external-mesa#73]
I'm trying to launch a game (https://github.com/ezQuake/ezquake-source) and I get a segfault in this function:
![gdbgui3](https://user-images.githubusercontent.com/8574092/37570602-f915b6fe-2aae-11e8-9f64-96a1b7318525.png)

Could you give any hints to help me find out why this is occurring? Is there information I can give that helps you track whether this is a real bug or a usage problem?

**Comment by kalyankondapally** [comment]
@sevagh Which OS ?

**Comment by sevagh** [comment]
This is in a Docker container (Ubuntu 18 Bionic) with a GPU passthrough from my Fedora 27 host, Linux x86_64:

```
set docker_exec_args "-e XDG_RUNTIME_DIR=/tmp \
        --privileged \
        -e WAYLAND_DISPLAY=$::env(WAYLAND_DISPLAY) \
        -v $::env(XDG_RUNTIME_DIR)/$::env(WAYLAND_DISPLAY):/tmp/$::env(WAYLAND_DISPLAY) \
        --device /dev/video0 \
        --device /dev/snd \
        --device /dev/shm \
        --device /dev/dri/card0 \
        --device /dev/fb0 \
        --device /dev/dri/renderD128"
```

**Comment by tpalli** [comment]
If this is not Android related, please test with latest Mesa and if still happens, file a bug to https://bugs.freedesktop.org/

**Comment by kalyankondapally** [comment]
ya try mesa from https://cgit.freedesktop.org/mesa/mesa/ and see if this is reproducible and file bug for Mesa.

**Comment by tpalli** [comment]
Some more explanation: This github here is Android-IA Mesa tree and issues. For generic Linux support, please use freedesktop.org bugzilla. Thanks! I will close this.
