### ISSUE TITLE
[ww29] dEQP-GLES3.functional.shaders.preprocessor.builtin has 4 tests failed on andriod

### ISSUE THREAD

**Issue by jennycao** [intel/external-mesa#85]
4 testcases in CTSDeqpTestcases  are fail in ww29 mesa master branch tests on android P.

dEQP-GLES3.functional.shaders.preprocessor.builtin#line_and_file_expression_fragment | fail
dEQP-GLES3.functional.shaders.preprocessor.builtin#line_and_file_expression_vertex | fail
dEQP-GLES3.functional.shaders.preprocessor.builtin#line_expression_fragment | fail
dEQP-GLES3.functional.shaders.preprocessor.builtin#line_expression_vertex | fail

**Comment by kalyankondapally** [comment]
check with latest master now

**Comment by jennycao** [comment]
These 4 tests are fixed with this patch .
the new result on ww31 are 

dEQP-GLES3.functional.shaders.preprocessor.builtin#line_and_file_expression_fragment | Passed
dEQP-GLES3.functional.shaders.preprocessor.builtin#line_and_file_expression_vertex | Passed
dEQP-GLES3.functional.shaders.preprocessor.builtin#line_expression_fragment | Passed
dEQP-GLES3.functional.shaders.preprocessor.builtin#line_expression_vertex | Passed
