### ISSUE TITLE
[ww29] dEQP-GLES31.functional.debug.negative_coverage.get_error.buffer have 3 tests failed on android

### ISSUE THREAD

**Issue by jennycao** [intel/external-mesa#86]
3 tests failed on CTSDeqpTestcases dEQP-GLES31.functional.debug.negative_coverage.get_error.buffer tests

dEQP-GLES31.functional.debug.negative_coverage.get_error.buffer#readn_pixels | fail
dEQP-GLES31.functional.debug.negative_coverage.get_error.state#get_nuniformfv | fail
dEQP-GLES31.functional.debug.negative_coverage.get_error.state#get_nuniformiv | fail

**Comment by tpalli** [comment]
Do you have following commit in the CTS?

--- 8< ---
commit c693c85a5f9983caab94c3973e6dc0efaae57b0c
Author: Tapani Pälli <tapani.palli@intel.com>
Date:   Thu Apr 5 08:13:46 2018 +0300

    Prefer KHR entrypoints instead of EXT for robustness tests
    
    When resolving function entrypoints, framework resolves EXT
    entrypoints after KHR to the same pointers. There are drivers that
    implement only KHR entrypoints, prefer KHR over EXT so that KHR
    entrypoints will be the ones used if both extensions are supported
    by the driver.
    
    Components: OpenGL ES
    VK-GL-CTS issue: 1107
    
    Affects:
    KHR-NoContext.es32.robustness.getnuniform
    KHR-NoContext.es32.robustness.readnpixels
    
    Change-Id: Iec5f7cbdd53061e105b3445f7613ee41fccc4553
    Signed-off-by: Tapani Pälli <tapani.palli@intel.com>

**Comment by jennycao** [comment]
@tpalli I had check deqp repo,
this patch current only exist on deqp-dev branch.
 we use is a P preview version cts package, which is not cover this commit.
We will keep monitor this patch after android publish and new official cts for android P released.

**Comment by tpalli** [comment]
@jennycao OK thanks. It looks like it should eventually come since git tags for Android Pie have it, as example "android-9.0.0_r3" has it.

**Comment by jennycao** [comment]
you mean tag https://android.googlesource.com/platform/external/deqp/+/android-9.0.0_r3 ？
I have checked this tag, not include this patch.

**Comment by tpalli** [comment]
@jennycao Note that the commit has different SHA in that tree, it is ad02e8d4bcbb06c8b1be78c2f2a0f7dafabd27d8 there. If you search by my name you should see it.

**Comment by jennycao** [comment]
@tpalli we use android-cts 9.0_R1 offlicial release version to test again, this issue still could be reproduced.
you patch ad02e8d4bcbb06c8b1be78c2f2a0f7dafabd27d8 is included in this version.

**Comment by tpalli** [comment]
OK that is strange, I'll take a look what could be going wrong here.

**Comment by tpalli** [comment]
Ah sorry I got confused, ad02e8d4bcbb06c8b1be78c2f2a0f7dafabd27d8 is a separate fix, it does not fix this one ... it seems NONE of the Android tagged versions actually include the commit mentioned above ("Prefer KHR entrypoints instead of EXT for robustness tests"). It is only available in 'vk-gl-cts' suite master branch but not for example in dEQP. I will figure out why this is.

**Comment by tpalli** [comment]
This is the actual fix we need: https://gitlab.khronos.org/Tracker/vk-gl-cts/issues/1107

BUT having said that, there is now a patch in mesa-dev list that will fix this also!

**Comment by tpalli** [comment]
This is fixed in Mesa master, please update/rebase Mesa to fix this.

**Comment by strassek** [comment]
@tpalli Could you share the commit id of the upstream fix?

edit: Never mind, easy find: https://cgit.freedesktop.org/mesa/mesa/commit/?id=37eee90df730ac6ba371b2ba8e61a1db9e55d7df
I'll get this merged and into testing. Thanks!

**Comment by strassek** [comment]
@jennycao This should now be fixed in master, please retest

**Comment by jennycao** [comment]
@strassek @tpalli  this 3 tests are fixed by 2eaf0f656cd5e07ab8e447b0309286e889e1b5b5,
We retest these 3 tests and got pass
Thanks for include the fix :)
