### ISSUE TITLE
[ww33] dEQP-VK.api.info.device#extensions failed on android

### ISSUE THREAD

**Issue by jennycao** [intel/external-mesa#89]
CTS version: 9.0_R1
Following test failed.
dEQP-VK.api.info.device#extensions | fail

**Comment by tpalli** [comment]
This fails because Mesa implements various Vulkan extensions that Android test is not aware of. I'm not sure we want to 'fix this'. In practice it seems to be enough to make this pass when I disable VK_KHR_8bit_storage and VK_KHR_create_renderpass2 extensions.

**Comment by renchenglei** [comment]
@tpalli CTS ask to 100% PASS on Android. So I am afraid we have to fix this issue. If this is one defect in test case side, could we try to prepare one PR for it?

**Comment by tpalli** [comment]
Hmm actually now when I run this passes for me. When I compile dEQP from P sources and run tests with 'dEQP-VK.api.info*extensions' I get total 4 passing tests.

**Comment by renchenglei** [comment]
@tpalli We used Google official released CTS package, and I got 3/4 pass. You could get it from https://source.android.com/compatibility/cts/downloads. Not sure, if there is new changes from test case side, I will check it. :)

**Comment by tpalli** [comment]
@renchenglei ok, maybe they've updated the test, I can prepare a PR that makes this test pass meanwhile

**Comment by tpalli** [comment]
@renchenglei nevermind, I had the fix in place when testing, I'll send the fix.

**Comment by tpalli** [comment]
https://github.com/intel/external-mesa/pull/96

**Comment by renchenglei** [comment]
@tpalli Ok, that's great! Thanks for the fix! :)

**Comment by strassek** [comment]
@jennycao This should now be fixed in master, please retest.

**Comment by jennycao** [comment]
@strassek @renchenglei  this test is passed on ww36's deqp tests.
after the fix patch #96 merged 
Thanks for the fix
