### ISSUE TITLE
[ww33]dEQP-VK.wsi.android.display_timing have 4 tets failed on android

### ISSUE THREAD

**Issue by jennycao** [intel/external-mesa#91]
dEQP-VK.wsi.android.display_timing.fifo#display_timing | fail
dEQP-VK.wsi.android.display_timing.fifo#reference | fail
dEQP-VK.wsi.android.display_timing.mailbox#display_timing | fail
dEQP-VK.wsi.android.display_timing.mailbox#reference | fail

**Comment by strassek** [comment]
These are all failing with VK_IMAGE_USAGE_STORAGE_BIT unsupported for gralloc swapchain

**Comment by strassek** [comment]
@jennycao This should now be fixed in master, please retest.

**Comment by jennycao** [comment]
@strassek this issue is fixed by  #100, we retest and got pass, Thanks for the fix :)
