### ISSUE TITLE
[ww33] dEQP-VK.wsi.android.swapchain have 2 tests failed on android

### ISSUE THREAD

**Issue by jennycao** [intel/external-mesa#92]
dEQP-VK.wsi.android.swapchain.create#image_usage | fail
dEQP-VK.wsi.android.swapchain.simulate_oom#image_usage | fail

**Comment by tpalli** [comment]
In both of these cases only 1 subtest of total 10 tests fail and both of these failures I believe happen because Mesa Vulkan HAL module does not support using VK_IMAGE_USAGE_STORAGE_BIT in swapchain images. I'm not sure what is required to add such support.

**Comment by strassek** [comment]
@jennycao This should now be fixed in master, please retest.

**Comment by jennycao** [comment]
@strassek this issue is fixed by #100, we retest and got pass, Thanks for the fix :)
