### ISSUE TITLE
[ww33] dEQP-GLES31.functional.ssbo.layout.random.all_shared_buffer.23 timeout on x86_64 abl

### ISSUE THREAD

**Issue by jennycao** [intel/external-mesa#94]
In ww33 CTSDeqpTestcases test,
dEQP-GLES31.functional.ssbo.layout.random.all_shared_buffer.23 got failed on x86_64 abl and pass on x86 abl.
in deqp framework test,
dEQP-GLES31.functional.ssbo.layout.random.all_shared_buffer.23 got timeout when run in batch and individual.
If I test with ww29 image, this case can pass sometime, timeout sometime with deqp framework.

So I guess some change make the dEQP-GLES31.functional.ssbo.layout.random.all_shared_buffer.23  execution time may take longer time than ww29, and exceed  the deqp test timeout limitation.

@renchenglei  Could you help to do further investigation ?

**Comment by jennycao** [comment]
I also found a bug on fdo https://bugs.freedesktop.org/show_bug.cgi?id=104981 
That this dEQP-GLES31.functional.ssbo.layout.random.all_shared_buffer.23 would take 54s to completed on BSW. it is quite a bit over.

**Comment by jennycao** [comment]
The logcat log are
`
12-31 16:02:16.193  3381  3658 I ActivityManager: START u0 {flg=0x10000000 cmp=com.drawelements.deqp/android.app.NativeActivity (has extras)} from uid 10112
12-31 16:02:16.227  3381  3420 I ActivityManager: Start proc 10209:com.drawelements.deqp:testercore/u0a112 for activity com.drawelements.deqp/android.app.NativeActivity
12-31 16:02:25.999  3381  3658 I ActivityManager: Process com.drawelements.deqp:testercore (pid 10209) has died: cch  CRE 
12-31 16:02:25.999  3381  3845 I WindowManager: WIN DEATH: Window{3310592 u0 com.drawelements.deqp/android.app.NativeActivity}
12-31 16:03:18.336  3381  3658 I ActivityManager: START u0 {flg=0x10000000 cmp=com.drawelements.deqp/.execserver.ServiceStarter (has extras)} from uid 2000
12-31 16:03:18.366  3381  3574 I ActivityManager: START u0 {flg=0x10000000 cmp=com.drawelements.deqp/android.app.NativeActivity (has extras)} from uid 10112
12-31 16:03:18.408  3381  3420 I ActivityManager: Start proc 11259:com.drawelements.deqp:testercore/u0a112 for activity com.drawelements.deqp/android.app.NativeActivity
12-31 16:03:49.723  3381  3574 I ActivityManager: Process com.drawelements.deqp:testercore (pid 11259) has died: fore TOP 
12-31 16:03:49.724  3381  3574 W ActivityManager: Force removing ActivityRecord{82761b5 u0 com.drawelements.deqp/android.app.NativeActivity t26}: app died, no saved state
12-31 16:03:49.724  3381  3658 I WindowManager: WIN DEATH: Window{a5f5323 u0 com.drawelements.deqp/android.app.NativeActivity}
`

**Comment by renchenglei** [comment]
Thanks @jennycao! It seems that "WIN DEATH"? I will take a look this issue.

**Comment by jennycao** [comment]
this test are passed on both x86 and x86_64 on ww36 weekly tests. so close this bug

**Comment by jennycao** [comment]
this test got failed on x86_64 again(timeout) in ww37's tests.
reopen it .

**Comment by strassek** [comment]
I'm not hitting this on master.

**Comment by jennycao** [comment]
Kevin, Thanks for update, I will close this old issue.
